sudo: required

services:
  - docker

language: node_js
node_js:
  - "7.4"

install:
  - ./CI/install

env:
  - TEST_NAME="first-test"          TEST_LANG="java" TEST_TYPE="basic" VIDEO="true"
  - TEST_NAME="first-test"          TEST_LANG="js"   TEST_TYPE="basic" VIDEO="true"

script:
  - ./CI/script

after_script:
  - ./CI/script_archive
  - ./CI/after_script
